version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@radix-ui/*"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "cmcal"
    assignees:
      - "cmcal"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"