# Robust Sequential Optimization Script with BMAD Integration
# UTF-8 encoding with proper error handling
# Generated by Claude Code with BMAD Framework

param(
    [string]$Mode = "sequential",
    [switch]$SkipTests = $false,
    [switch]$SecurityOnly = $false
)

$ErrorActionPreference = "Continue"
$OutputEncoding = [System.Text.Encoding]::UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   BMAD OPTIMIZATION SYSTEM v2.0" -ForegroundColor Cyan  
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Yellow
Write-Host "Mode: $Mode" -ForegroundColor Yellow
Write-Host ""

# Create log directory
$timestamp = Get-Date -Format 'yyyy-MM-dd-HHmm'
$logDir = "optimization-logs/$timestamp"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

# Results tracking
$results = @{
    Success = 0
    Failed = 0
    Skipped = 0
    Tasks = @()
}

function Write-TaskResult {
    param(
        [string]$Task,
        [bool]$Success,
        [string]$Message = ""
    )
    
    if ($Success) {
        Write-Host "[OK] $Task" -ForegroundColor Green
        $results.Success++
    } else {
        Write-Host "[FAILED] $Task - $Message" -ForegroundColor Red
        $results.Failed++
    }
    
    $results.Tasks += @{
        Name = $Task
        Success = $Success
        Message = $Message
        Timestamp = Get-Date
    }
}

# Phase 1: Rebuild Native Bindings
Write-Host "PHASE 1: REBUILDING NATIVE BINDINGS" -ForegroundColor Cyan
Write-Host "------------------------------------" -ForegroundColor DarkCyan

try {
    & npm rebuild @swc/core 2>&1 | Out-File "$logDir/rebuild.log"
    Write-TaskResult -Task "Rebuild @swc/core" -Success $true
} catch {
    Write-TaskResult -Task "Rebuild @swc/core" -Success $false -Message $_.Exception.Message
}

# Phase 2: Security Scan
Write-Host ""
Write-Host "PHASE 2: SECURITY & COMPLIANCE" -ForegroundColor Cyan
Write-Host "------------------------------------" -ForegroundColor DarkCyan

try {
    $securityResult = & node scripts/security-dependency-scan.cjs 2>&1
    $securityResult | Out-File "$logDir/security.log"
    
    if ($securityResult -match "Status: COMPLIANT") {
        Write-TaskResult -Task "Security Scan" -Success $true
    } else {
        Write-TaskResult -Task "Security Scan" -Success $false -Message "Non-compliant"
    }
} catch {
    Write-TaskResult -Task "Security Scan" -Success $false -Message $_.Exception.Message
}

# Phase 3: BMAD Agents
Write-Host ""
Write-Host "PHASE 3: BMAD AGENT DEPLOYMENT" -ForegroundColor Cyan
Write-Host "------------------------------------" -ForegroundColor DarkCyan

$bmadAgents = @(
    @{Name="Byzantine Validator"; Command="node .bmad-core/bmad.js agent byzantine-validator"},
    @{Name="CloudTrail Auditor"; Command="node .bmad-core/bmad.js agent cloudtrail-auditor"},
    @{Name="PHI Guardian"; Command="node .bmad-core/bmad.js agent phi-guardian"}
)

foreach ($agent in $bmadAgents) {
    try {
        Write-Host "Deploying $($agent.Name)..." -NoNewline
        $output = Invoke-Expression $agent.Command 2>&1
        $output | Out-File "$logDir/$($agent.Name -replace ' ', '-').log"
        Write-TaskResult -Task $agent.Name -Success $true
    } catch {
        Write-TaskResult -Task $agent.Name -Success $false -Message $_.Exception.Message
    }
}

if (-not $SecurityOnly) {
    # Phase 4: Code Quality
    Write-Host ""
    Write-Host "PHASE 4: CODE QUALITY" -ForegroundColor Cyan
    Write-Host "------------------------------------" -ForegroundColor DarkCyan
    
    try {
        Write-Host "Running ESLint auto-fix..." -NoNewline
        $lintOutput = & npm run lint:fix 2>&1
        $lintOutput | Out-File "$logDir/lint.log"
        
        if ($LASTEXITCODE -eq 0) {
            Write-TaskResult -Task "ESLint Fix" -Success $true
        } else {
            Write-TaskResult -Task "ESLint Fix" -Success $false -Message "Some issues remain"
        }
    } catch {
        Write-TaskResult -Task "ESLint Fix" -Success $false -Message $_.Exception.Message
    }
    
    try {
        Write-Host "Running TypeScript check..." -NoNewline
        $tscOutput = & npm run typecheck 2>&1
        $tscOutput | Out-File "$logDir/typecheck.log"
        
        if ($LASTEXITCODE -eq 0) {
            Write-TaskResult -Task "TypeScript Check" -Success $true
        } else {
            Write-TaskResult -Task "TypeScript Check" -Success $false -Message "Type errors found"
        }
    } catch {
        Write-TaskResult -Task "TypeScript Check" -Success $false -Message $_.Exception.Message
    }
}

if (-not $SkipTests -and -not $SecurityOnly) {
    # Phase 5: Testing
    Write-Host ""
    Write-Host "PHASE 5: TEST EXECUTION" -ForegroundColor Cyan
    Write-Host "------------------------------------" -ForegroundColor DarkCyan
    
    try {
        Write-Host "Running unit tests..." -NoNewline
        $testOutput = & npm run test:unit 2>&1
        $testOutput | Out-File "$logDir/tests-unit.log"
        
        if ($LASTEXITCODE -eq 0) {
            Write-TaskResult -Task "Unit Tests" -Success $true
        } else {
            Write-TaskResult -Task "Unit Tests" -Success $false -Message "Some tests failed"
        }
    } catch {
        Write-TaskResult -Task "Unit Tests" -Success $false -Message $_.Exception.Message
    }
}

# Phase 6: Performance Analysis
Write-Host ""
Write-Host "PHASE 6: PERFORMANCE ANALYSIS" -ForegroundColor Cyan
Write-Host "------------------------------------" -ForegroundColor DarkCyan

try {
    Write-Host "Running BMAD performance analysis..." -NoNewline
    $perfOutput = & node .bmad-core/bmad.js analyze 2>&1
    $perfOutput | Out-File "$logDir/performance.log"
    Write-TaskResult -Task "Performance Analysis" -Success $true
} catch {
    Write-TaskResult -Task "Performance Analysis" -Success $false -Message $_.Exception.Message
}

# Generate Report
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "   OPTIMIZATION COMPLETE" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green

$report = @"
# BMAD Optimization Report
Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Summary
- Successful Tasks: $($results.Success)
- Failed Tasks: $($results.Failed)
- Success Rate: $([math]::Round(($results.Success / ($results.Success + $results.Failed)) * 100))%

## Task Details
$(foreach ($task in $results.Tasks) {
    if ($task.Success) {
        "✅ $($task.Name)"
    } else {
        "❌ $($task.Name): $($task.Message)"
    }
})

## Logs Directory
$logDir

## Next Steps
$(if ($results.Failed -gt 0) {
    "- Review failed tasks in log files"
    "- Run 'npm audit fix' for remaining issues"
    "- Check TypeScript configuration"
} else {
    "- All optimizations successful!"
    "- Ready for deployment"
})
"@

$report | Out-File "$logDir/report.md" -Encoding UTF8

Write-Host ""
Write-Host "Success: $($results.Success) | Failed: $($results.Failed)" -ForegroundColor $(if ($results.Failed -eq 0) { "Green" } else { "Yellow" })
Write-Host "Report: $logDir/report.md" -ForegroundColor Cyan
Write-Host ""

# Return exit code
if ($results.Failed -eq 0) {
    exit 0
} else {
    exit 1
}