apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: prometheus
    access: proxy
    org_id: 1
    url: http://prometheus:9090
    is_default: true
    version: 1
    editable: false
    json_data:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      timeInterval: 15s

  - name: 'Loki'
    type: loki
    access: proxy
    org_id: 1
    url: http://loki:3100
    version: 1
    editable: false
    json_data:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'prometheus'
          matcherRegex: 'traceID=(\\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'

  - name: 'AlertManager'
    type: alertmanager
    access: proxy
    org_id: 1
    url: http://alertmanager:9093
    version: 1
    editable: false
    json_data:
      implementation: prometheus

  - name: 'Postgres'
    type: postgres
    access: proxy
    org_id: 1
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_MONITORING_USER}
    password: ${POSTGRES_MONITORING_PASSWORD}
    version: 1
    editable: false
    json_data:
      sslmode: require
      maxOpenConns: 5
      maxIdleConns: 2
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false