
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Prefer env vars in production, fall back to embedded public credentials
// Note: Use process.env in tests/Node to avoid import.meta issues
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const VITE_ENV: any = (typeof process !== 'undefined' ? process.env : {}) || {};

function sanitize(value: unknown): string {
  return (value ?? '').toString().trim();
}

function isValidUrl(value: string): boolean {
  try { new URL(value); return true; } catch { return false; }
}

const ENV_URL = sanitize(VITE_ENV.VITE_SUPABASE_URL);
const ENV_KEY = sanitize(VITE_ENV.VITE_SUPABASE_ANON_KEY);

const SUPABASE_URL = isValidUrl(ENV_URL) ? ENV_URL : 'https://tqyiqstpvwztvofrxpuf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = ENV_KEY.length > 10 ? ENV_KEY : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxeWlxc3Rwdnd6dHZvZnJ4cHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODIxNzksImV4cCI6MjA2NDg1ODE3OX0.EJPmyjD9cpZDa_PjxKkUiVpKfVmFAFofNSk58Ssqp_8';

// Note: These are public client-side values (anon key) safe to expose in frontend
// If you deploy elsewhere, configure env vars in your hosting platform.
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Handle localStorage for both browser and test environments
const getStorage = () => {
  if (typeof window !== 'undefined' && window.localStorage) {
    return window.localStorage;
  }
  // Return a mock storage for test environment
  return {
    getItem: () => null,
    setItem: () => {},
    removeItem: () => {},
    clear: () => {}
  };
};

// Use untyped client in tests to avoid strict relation-name overloads
export const supabase: any = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // Enhanced security configuration
    flowType: 'pkce'
  },
  // Performance optimizations
  db: {
    schema: 'public'
  },
  global: {
    // Set fetch timeout to 15 seconds
    fetch: (url: RequestInfo | URL, init?: RequestInit) => {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000);
      
      return fetch(url, {
        ...init,
        signal: controller.signal
      }).finally(() => clearTimeout(timeoutId));
    }
  },
  // Connection pooling
  realtime: {
    params: {
      eventsPerSecond: 2, // Rate limit realtime events
      timeout: 10000 // 10 second timeout for realtime connections
    }
  }
});
